export const BRIGHTCOVE_LIVE_ACCOUNT_ID =
  process.env.BRIGHTCOVE_LIVE_ACCOUNT_ID ?? "6416149296001";

export const BRIGHTCOVE_LIVE_PLAYER_ID =
  process.env.BRIGHTCOVE_LIVE_PLAYER_ID ?? "nJQN4AMQl";

export const BRIGHTCOVE_LIVE_VIDEO_ID =
  process.env.BRIGHTCOVE_LIVE_VIDEO_ID ?? "6397475321112";

export const BRIGHTCOVE_LIVE_PLAYBACK_TOKEN =
  process.env.BRIGHTCOVE_LIVE_PLAYBACK_TOKEN ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtbiI6InBsYXlsaXN0IiwiaXNzIjoiYmxpdmUtcGxheWJhY2stbWFuYWdlbWVudC1hcGkiLCJzdWIiOiJwbGF5YmFja3Rva2VuIiwiYXVkIjpbIjY0MTYxNDkyOTYwMDEiXSwianRpIjoiNjM5NzQ3NTMyMTExMiJ9.WxkA2udhcLfGDZcnWwBbg52PiItL4RCyT1NdyBIT4KU";

export const BRIGHTCOVE_LIVE_PLAYER_SCRIPT = `https://players.brightcove.net/${BRIGHTCOVE_LIVE_ACCOUNT_ID}/${BRIGHTCOVE_LIVE_PLAYER_ID}_default/index.min.js`;
