export const BRIGHTCOVE_HIGHLIGHTS_ACCOUNT_ID =
  process.env.NEXT_PUBLIC_BRIGHTCOVE_HIGHLIGHTS_ACCOUNT_ID?.trim() ?? "6416149296001";

export const BRIGHTCOVE_HIGHLIGHTS_PLAYER_ID =
  process.env.NEXT_PUBLIC_BRIGHTCOVE_HIGHLIGHTS_PLAYER_ID?.trim() ?? "3bs0mSY6W";

export const BRIGHTCOVE_HIGHLIGHTS_PLAYLIST_ID =
  process.env.NEXT_PUBLIC_BRIGHTCOVE_HIGHLIGHTS_PLAYLIST_ID?.trim() ?? "1868092820137994743";
